baseURL = 'https://techunder.tech/'
languageCode = 'zh-CN'
title = 'Techunder'
theme = 'hugo-book'

[params]
  BookSection = '*'
  BookToC = true
  BookLogo = 'logo.png'

[markup.tableOfContents]
  startLevel = 4
  endLevel = 5
  ordered = false