baseURL = 'https://techunder.tech/'
languageCode = 'zh-CN'
title = 'Techunder'
theme = 'hugo-book'

[params]
  BookSection = '*'
  BookToC = true
  BookLogo = 'logo.png'

[markup.tableOfContents]
  startLevel = 1
  endLevel = 2
  ordered = false

[markup.goldmark.renderer]
  unsafe = true